language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -e .
- pip install pytest pytest-cov coveralls flake8
env:
- TEST_ENV=travis
script:
- flake8 . && travis_wait 50 py.test
before_install:
- openssl aes-256-cbc -K $encrypted_ad73325f33e8_key -iv $encrypted_ad73325f33e8_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
- mkdir -p ~/mdf/credentials/
- mv MDF_Forge_tokens.json ~/mdf/credentials/MDF_Forge_tokens.json
after_success:
- coveralls
notifications:
  email:
    recipients:
    - jgaff@uchicago.edu
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: PeTw4hgPe/UvQXjmYD7tT+4J1tOZKOHw5sLYegSZtnekKeLpjLZib0eZrAkzE5LFbRoRgXZ9z4Yn+hN3az4Z1GodXYcRrYrvRwe75oZMgxe5TvXpmE1lqv8nCvbDo2LJbkVTdn0fKRRfEl1W62RtYcyh+QwunUudHA9U2zOZLqSt4BeYMTOK4T5XyhZ5T1DYSBO8Dj28OFuemjwGkBMgZ5Z/+GqIJ1wZw2sKHKN+vkKj8NChPEzok+GX0R1CXgqvMMHPNJUx/69hZMuqxZciQICqhAstUw//ssTI6bzGHivbhObE5nlDqmBIPDD8tEG6p/XOOFtHx2a/R6KV+5wjzIs6sLiEz2QAG/qKm20jSHi8j585RqjgpBGC1g0FQ8k75E0oF8ls5unHFnDHPRWnPI0ifZ2qgYIUWdHC6dV4QF06Z1OYRHfOiyiLvuWIlKufKRM6aC84LEXxBS7Lq4MUZ+wKjGVf5EmSeJzYC+NXnBcnkFOx3KnImNDP9JuBwsgrFYRZhpvlwKdmCn1sw+iAuhco+nTKrzq5fK4vglE4zAMr81YgnLrVY3xJrz0G4wbQYvtxcFx84GaV6UiL1hfbuu4aBw3o6kuq5gxEaYg18MvsIZyIbQOpNuqRtQsHknRJSoLPvIEv8Rq6zA2twHI1MJXunjzsc0WaCm2Npt1ZpGk=
deploy:
  provider: pypi
  user: jgaff
  on:
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: wT5WAIDdm7HWC4p3XBf1SH3tyCSHT6i9+XzfoZUvNrdOjb41tbrovydhW/vl+ZjbYUOnadC4pl1P56HwegmToWAKPoeGrr1XdAoSBgRdsizXUD3E21KbGJpY32d8yDh5BX2FkHfW2GgrhS17he142bA970Px/9+5f8hrGRY9+T09+h2olFYxNEZRcKNDHs3YVXfhXMABZr0qzJLCWAebGvrlBpdZS0SYuJZhiCveixow5ZjR4ZImOFhJd1XxKZLWp5I78zFgHquNJwj2lejwvHyCc7wKOC/dH9Ctcx2eLiTFm4alhYSNy2a9ySh1YhnmbhVEohVV9N9c9N/Og5pnbkhZ2kbi6TSa7mnTFFjRS5tvXfFtYMBZZog6qlAuisSEJ/tAGbZILIs7kT41pzCnLGwhR1xAEN023LNlLsqUJNP0nvMNArSVylhUySaxVphs13csimnPA/URl8RvpgIEDb4pja4W7YRl4ZWU6wjrFM0ux571aF6WQBeCtMgq4pU9n55ccctHvjAAfi/jZsjlYi3KcJkgUwy8o3RPREM0lCuS/faWiaCQtPcH02muBRSEZksUnpbZW2X+bi8izmH4ZUN3DkqHxs6w/v9iXLnob/gjX1W+TtafLqWH6sDAF0FHZZi8FT5w5HjuT4BRPg4CIvnAQ2tNdQj/NulzJ8qfpek=
