language: python
python:
- '2.6'
- '2.7'
- '3.0'
- '3.1'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pytest pytest-cov coveralls
- pip install -e .
env:
- TEST_ENV=travis
script:
- travis_wait 50 py.test
before_install:
- openssl aes-256-cbc -K $encrypted_4b438100ad6f_key -iv $encrypted_4b438100ad6f_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
- mkdir -p ~/mdf/credentials/
- mv MDF_Forge_tokens.json ~/mdf/credentials/MDF_Forge_tokens.json
after_success:
- coveralls
notifications:
  email:
    recipients:
    - jgaff@uchicago.edu
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: vYpU1qxCSx8OMQsHBEfLZP6foqd88Xon54kejUNzMKR6BpOS0rgJZmY1VYKgqd8gWxAox3WyYDyIzEsEO/b0JQ4l53hC9A1Hk0F5YCTm9NjPIb0boIpJ2MbIuijnDAJEEiruevQKH+esmbOssGSg8bDyCd8V1vWrvCEe84pIbfsevIyuUnRWKpEIHk/oIDliUy9d8HhNJLGuJrKnIHtMFw+fkO36yQMxM5SDXuM6yvBXr3+7ntqeZXthYogmKLn1fu+X/V9v8Zz2MlfZmY9G5q3RSJAlC4ASeFLF8GNBZHsRBlGPvF8RNtRiiUlxXmYOes7B61SD3sHVAMvNhSS2xL0LGNU9ZzUWx8HVwlt60ATOF7aOu2Uao3SVWMi50ZC0DfRlUw11gNOyyMFq5zsHK32HeFm81o/TvSr/Iy4Xy8j/psX/38T9MjrgFxPneOolUIBjAeW27kW/39qfLLtPOqA3wmByucmiQTJXJhpIbiEKfnliERxbp5gGdFg0DZKQKWNikxjhUJXKU4EF5FC7m9KgqkgvfcnhhEoz6moRBDAjC9/xr9xIYFDa5bIYuB98gGWle452pUr3x5Br1SvS7RfA42Ob2G2U11T/GQ+uEmXy1Ai5emrxjF10qfXY1j7Oe1MbKNqR/C/n3Z3xjduX3LDSkskvcClqmi9cFuMX3Kk=
deploy:
  provider: pypi
  user: jgaff
  on:
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: Bao2ot8PG8VX8EjzQ9kgLmzQIkepGf4o3VPM1IhUuYjlos3cpVtCn1Vqn1GLShdJzKXrgkAo12A0qkxt9T0Mx/hwYtkY4mlg/0wTo8DAKq96Gy6kjb9xlXw+DpeoVwHOUkibCRIPd+QC3z5Ut36l/xAR31xJ8BDhIkD7MaVZXwgB2ykG3tElL63peFCMVPhS7HmZ9Hf+11b73MPdlG8j/gNReDtd9vCU/LmGrjiHukB3nQLYmmVnCvbfwQdUJ3t2B9BpNlRUwcfqLOyTFIQoWlo+GkkyhTsafWEhHMQgsZvcti5PPlgbUSrUK1fUc5+/gRRsn6RJ0Bof+njXmgVmgOA4XGRsO+/L4Dfe9gXAleR1lx/lIzkh9hPot870w+65WIQs4tdSx9cShXHx+d6uv3eWkzPhCzWZwrK5DL4M5oXRSpojA8MPzuYsTsWaOdCHXj6g7KymdHRqgi7QPWJGvOf/Gs+xHaLcSKMZz/uLBVFyTCjcy3vyv48n3HljZTLYNp6tpV77Yo5i/qNtQJ7Tb853L/iBosGQd2DMVxGvbJbhu7grdgA5wt/nGOKLNLDYc7AmgSQoWh3un5/c0cTQYQo8e13fLC43FTKTQthsalZNBfLcaCDVJ6KvKMh/kF11pYfTQ8hDzpGsFklthXvu9zggS1I4sHwbYjb6Z7lAle0=
