language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -e .
- pip install pytest pytest-cov coveralls
env:
- TEST_ENV=travis
script:
- travis_wait 50 py.test
before_install:
- openssl aes-256-cbc -K $encrypted_ad73325f33e8_key -iv $encrypted_ad73325f33e8_iv
  -in travis.tar.enc -out travis.tar -d
- tar xvf travis.tar
- mkdir -p ~/mdf/credentials/
- mv MDF_Forge_tokens.json ~/mdf/credentials/MDF_Forge_tokens.json
after_success:
- coveralls
notifications:
  email:
    recipients:
    - jgaff@uchicago.edu
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always
    rooms:
      secure: PeTw4hgPe/UvQXjmYD7tT+4J1tOZKOHw5sLYegSZtnekKeLpjLZib0eZrAkzE5LFbRoRgXZ9z4Yn+hN3az4Z1GodXYcRrYrvRwe75oZMgxe5TvXpmE1lqv8nCvbDo2LJbkVTdn0fKRRfEl1W62RtYcyh+QwunUudHA9U2zOZLqSt4BeYMTOK4T5XyhZ5T1DYSBO8Dj28OFuemjwGkBMgZ5Z/+GqIJ1wZw2sKHKN+vkKj8NChPEzok+GX0R1CXgqvMMHPNJUx/69hZMuqxZciQICqhAstUw//ssTI6bzGHivbhObE5nlDqmBIPDD8tEG6p/XOOFtHx2a/R6KV+5wjzIs6sLiEz2QAG/qKm20jSHi8j585RqjgpBGC1g0FQ8k75E0oF8ls5unHFnDHPRWnPI0ifZ2qgYIUWdHC6dV4QF06Z1OYRHfOiyiLvuWIlKufKRM6aC84LEXxBS7Lq4MUZ+wKjGVf5EmSeJzYC+NXnBcnkFOx3KnImNDP9JuBwsgrFYRZhpvlwKdmCn1sw+iAuhco+nTKrzq5fK4vglE4zAMr81YgnLrVY3xJrz0G4wbQYvtxcFx84GaV6UiL1hfbuu4aBw3o6kuq5gxEaYg18MvsIZyIbQOpNuqRtQsHknRJSoLPvIEv8Rq6zA2twHI1MJXunjzsc0WaCm2Npt1ZpGk=
deploy:
  provider: pypi
  user: jgaff
  on:
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: tyR9ZrsTzyh1KRUeO0ushTPfO7EqAsEq7Tdqn/IaGjQZqLpSdsoU7t8+m95kLYFesG0xmPcY/Y0NN4wXEiq4B42+WZJUTEnoe+9Uj6ipXzYcjM8avniwpYk9qzCP7bfLRTOVWxtSeXPAt7BAVqLnKEyLFDEW70b3GlU690v9zyQWJ/cP3oHyUq0R8/1IAvKBNc8Ce5Tn10Y1vGJcA2LYjlLtxChq4rLCcUULapB0MFTj6Q061UZqOtoBJXV7lOegrBCHWRAtTF2GnJAI+RWT1V7hWZcskeI+GmWgMIVTpbXgTMkG9mS1J7M+l3if36XUJTywuoC0KYurr37m6wMWeusOeiUi2JR/oCT8mPvTo3Ixl3ezs0uSZeif1Cwj2vzqd1XaueZtTAgbj/MCzvfbX1Zjwl7d3gNp4J7Ou+WQD6z0Rl62DrR6ncBgQTCs33eRU8nvmFf1aZkasCcudVlroxnwy4pNnRlZUdkXtSw88gWVAQ/L4POjjUhwQbn7Y5dn6dEcGCB4JgyQlcl1ck1qtCpRKkgc5mcEsS12Rm7zGhPWEDbA1U4zdcpKAePp9PfxQrIQJH/kSPDsNBvSxaj2wQPMB30pOrvxYleOIyuPHCM8LgxVrMi7Wz2aZc/u36i5IlnrCr5xybKlgAZU7uW39sUYrxPdP4G+pq3GNvnALbk=
